# Generated by Django 2.2 on 2019-04-18 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('STalk', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreateDj',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DJ_name', models.CharField(max_length=20)),
                ('deejay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='STalk.Deejay')),
            ],
        ),
    ]
