# Generated by Django 2.2 on 2019-04-19 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('STalk', '0004_auto_20190419_0951'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreateSpeaker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=20)),
                ('speaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='STalk.Speakers')),
            ],
        ),
    ]
