# Generated by Django 2.2 on 2019-04-23 16:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('STalk', '0005_createspeaker'),
    ]

    operations = [
        migrations.AddField(
            model_name='deejay',
            name='contact',
            field=models.IntegerField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deejay',
            name='email',
            field=models.EmailField(default=django.utils.timezone.now, max_length=254),
            preserve_default=False,
        ),
    ]
