# Generated by Django 2.2 on 2019-04-30 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('STalk', '0008_createmc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hype',
            name='user',
        ),
    ]
