# Generated by Django 2.2 on 2019-05-02 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('STalk', '0009_remove_hype_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planner',
            name='user',
        ),
    ]
