# Generated by Django 2.2 on 2019-05-05 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('STalk', '0010_remove_planner_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CreateDj',
        ),
    ]
